import type { ICartCatalog } from "@/types/cartItem";

export const dummyCartItems: ICartCatalog = [
  {
    id: "p002",
    name: "Snake Plant (Sansevieria)",
    image: "https://images.pexels.com/photos/416468/pexels-photo-416468.jpeg",
    price: 29.5,
    quantity: 2,
    size: "Small",
    potColor: "Terracotta",
  },
  {
    id: "p003",
    name: "Fiddle Leaf Fig",
    image: "https://images.pexels.com/photos/5699663/pexels-photo-5699663.jpeg",
    price: 59.0,
    quantity: 1,
    size: "Large",
    potColor: "Matte Black",
  },
  {
    id: "p004",
    name: "ZZ Plant (Zamioculcas)",
    image: "https://images.pexels.com/photos/5740746/pexels-photo-5740746.jpeg",
    price: 34.25,
    quantity: 1,
    size: "Medium",
    potColor: "Grey Stone",
  },
  {
    id: "p005",
    name: "Snake Plant (Sansevieria)",
    image: "https://images.pexels.com/photos/416468/pexels-photo-416468.jpeg",
    price: 29.5,
    quantity: 2,
    size: "Small",
    potColor: "Terracotta",
  },
  {
    id: "p006",
    name: "Fiddle Leaf Fig",
    image: "https://images.pexels.com/photos/5699663/pexels-photo-5699663.jpeg",
    price: 59.0,
    quantity: 1,
    size: "Large",
    potColor: "Matte Black",
  },
  {
    id: "p007",
    name: "ZZ Plant (Zamioculcas)",
    image: "https://images.pexels.com/photos/5740746/pexels-photo-5740746.jpeg",
    price: 34.25,
    quantity: 1,
    size: "Medium",
    potColor: "Grey Stone",
  },
  {
    id: "p008",
    name: "Snake Plant (Sansevieria)",
    image: "https://images.pexels.com/photos/416468/pexels-photo-416468.jpeg",
    price: 29.5,
    quantity: 2,
    size: "Small",
    potColor: "Terracotta",
  },
  {
    id: "p009",
    name: "Fiddle Leaf Fig",
    image: "https://images.pexels.com/photos/5699663/pexels-photo-5699663.jpeg",
    price: 59.0,
    quantity: 1,
    size: "Large",
    potColor: "Matte Black",
  },
  {
    id: "p010",
    name: "ZZ Plant (Zamioculcas)",
    image: "https://images.pexels.com/photos/5740746/pexels-photo-5740746.jpeg",
    price: 34.25,
    quantity: 1,
    size: "Medium",
    potColor: "Grey Stone",
  },
];
